-- Create the lifeblood_app table in livr.lifeblood schema
-- This script is executed by the Databricks Asset Bundle setup job

-- Drop existing table if it exists (to handle schema changes)
DROP TABLE IF EXISTS livr.lifeblood.lifeblood_app;

-- Create the new table with updated schema
CREATE TABLE livr.lifeblood.lifeblood_app (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    
    -- Form metadata
    form_date DATE NOT NULL,
    inspector_name STRING NOT NULL,
    user_email STRING NOT NULL,
    submission_time TIMESTAMP NOT NULL,
    
    -- Equipment condition checks
    donation_chairs_condition STRING NOT NULL,
    blood_collection_equipment_condition STRING NOT NULL,
    monitoring_devices_condition STRING NOT NULL,
    safety_equipment_condition STRING NOT NULL,
    
    -- Donor information and compliance
    donor_name STRING NOT NULL,
    donor_contact_number STRING NOT NULL,
    donor_health_screening_completed BOOLEAN NOT NULL,
    donor_consent_form_completed BOOLEAN NOT NULL,
    
    -- Additional notes
    notes STRING,
    
    -- System fields
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
) USING DELTA
TBLPROPERTIES (
  'delta.feature.allowColumnDefaults' = 'supported'
)
COMMENT 'Lifeblood Red Cross Australia donor center inspection and compliance form submissions';

-- DATABRICKS APPS PERMISSION MODEL: App Service Principal Proxy Pattern
-- The app service principal acts as a proxy for all authenticated users
-- Users authenticate through the app, and the app performs database operations on their behalf
-- This eliminates the need to grant individual database permissions to each user

-- Grant permissions to the app owner (for development and management)
GRANT USAGE ON CATALOG livr TO `olivia.ren@databricks.com`;
GRANT USAGE ON SCHEMA livr.lifeblood TO `olivia.ren@databricks.com`;
GRANT SELECT ON TABLE livr.lifeblood.lifeblood_app TO `olivia.ren@databricks.com`;
GRANT MODIFY ON TABLE livr.lifeblood.lifeblood_app TO `olivia.ren@databricks.com`;

-- Grant comprehensive permissions to the app service principal (proxy for all app users)
-- The app service principal needs full access to perform operations on behalf of authenticated users
GRANT USAGE ON CATALOG livr TO `33dae364-1f13-4996-9548-00be30f5d36a`;
GRANT USAGE ON SCHEMA livr.lifeblood TO `33dae364-1f13-4996-9548-00be30f5d36a`;
GRANT SELECT ON TABLE livr.lifeblood.lifeblood_app TO `33dae364-1f13-4996-9548-00be30f5d36a`;
GRANT MODIFY ON TABLE livr.lifeblood.lifeblood_app TO `33dae364-1f13-4996-9548-00be30f5d36a`;

-- Additional permissions for the service principal to manage the table structure if needed
GRANT CREATE ON SCHEMA livr.lifeblood TO `33dae364-1f13-4996-9548-00be30f5d36a`;
