# Databricks App Configuration for Streamlit
# This file configures how the Streamlit app runs in Databricks Apps

command:
  - "python"
  - "-m" 
  - "streamlit"
  - "run"
  - "streamlit_app.py"
  - "--server.port=8000"
  - "--server.address=0.0.0.0"
  - "--server.headless=true"
  - "--browser.gatherUsageStats=false"
  - "--server.enableCORS=false"
  - "--server.enableXsrfProtection=false"

env:
  - name: DATABRICKS_WAREHOUSE_HTTP_PATH
    value: "/sql/1.0/warehouses/4b9b953939869799"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "4b9b953939869799"
  - name: CATALOG_NAME
    value: "livr"
  - name: SCHEMA_NAME
    value: "lifeblood"
  - name: TABLE_NAME
    value: "lifeblood_app"
  - name: PYTHONPATH
    value: "/app"
  - name: DATABRICKS_APP_PORT
    value: "8000"